print('I was able to figure out the what went \n wrong with the first push now I am ready to try this again')